// <auto-generated />
using System;
using AccesoDatos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccesoDatos.Migrations
{
    [DbContext(typeof(GestorContextDB))]
    [Migration("20250619135543_UpdatePersonaEmpleadoID")]
    partial class UpdatePersonaEmpleadoID
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccesoDatos.Entidades.Categoria", b =>
                {
                    b.Property<long>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CategoriaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.DetallesVenta", b =>
                {
                    b.Property<long>("DetalleVentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_DetalleVenta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DetalleVentaId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<long>("IdProducto")
                        .HasColumnType("bigint")
                        .HasColumnName("id_Producto");

                    b.Property<long>("IdVenta")
                        .HasColumnType("bigint")
                        .HasColumnName("id_Venta");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("DetalleVentaId");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdVenta");

                    b.ToTable("DetallesVenta", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Empleado", b =>
                {
                    b.Property<long>("PersonaId")
                        .HasColumnType("bigint")
                        .HasColumnName("PersonaId");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaEgreso")
                        .HasColumnType("date")
                        .HasColumnName("fechaEgreso");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("fechaIngreso");

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("legajo");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("pass");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.Property<bool>("UsuarioEstaHabilitado")
                        .HasColumnType("bit")
                        .HasColumnName("usuarioestahabilitado");

                    b.HasKey("PersonaId");

                    b.ToTable("Empleados", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.EmpleadoRol", b =>
                {
                    b.Property<long>("EmpleadoRolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EmpleadoRolId"));

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("date");

                    b.Property<long>("IdEmpleado")
                        .HasColumnType("bigint");

                    b.Property<long>("IdRol")
                        .HasColumnType("bigint");

                    b.HasKey("EmpleadoRolId");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdRol");

                    b.ToTable("Empleados_Roles", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Marca", b =>
                {
                    b.Property<long>("MarcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MarcaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MarcaId");

                    b.ToTable("Marcas", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Movimiento", b =>
                {
                    b.Property<long>("MovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MovimientoId"));

                    b.Property<long?>("IdVenta")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoMovimiento")
                        .HasColumnType("int");

                    b.HasKey("MovimientoId");

                    b.HasIndex("IdVenta");

                    b.ToTable("Movimientos", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Persona", b =>
                {
                    b.Property<long>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PersonaId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cuil")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono2")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PersonaId");

                    b.ToTable("Personas", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Producto", b =>
                {
                    b.Property<long>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ProductoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductoId"));

                    b.Property<long?>("CategoriaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit")
                        .HasColumnName("esta_eliminado");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<long?>("IdCategoria")
                        .HasColumnType("bigint")
                        .HasColumnName("id_Categoria");

                    b.Property<long?>("IdMarca")
                        .HasColumnType("bigint")
                        .HasColumnName("id_Marca");

                    b.Property<long?>("MarcaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Medida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("medida");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_costo");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_venta");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("unidad_medida");

                    b.HasKey("ProductoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdMarca");

                    b.HasIndex("MarcaId");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Rol", b =>
                {
                    b.Property<long>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_Rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RolId"));

                    b.Property<long>("CodigoRol")
                        .HasColumnType("bigint")
                        .HasColumnName("codigo_rol");

                    b.Property<long>("DetalleRol")
                        .HasColumnType("bigint")
                        .HasColumnName("detalleRol");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("RolId");

                    b.HasIndex("CodigoRol")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.TipoPago", b =>
                {
                    b.Property<long>("TipoPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_TipoPago");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TipoPagoId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("detalle");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("TipoPagoId");

                    b.ToTable("TiposPago", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Venta", b =>
                {
                    b.Property<long>("VentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_Venta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VentaId"));

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("detalle");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("date")
                        .HasColumnName("fecha_venta");

                    b.Property<long>("IdEmpleado")
                        .HasColumnType("bigint")
                        .HasColumnName("id_Empleado");

                    b.Property<string>("NumeroVenta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("numeroVenta");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.HasKey("VentaId");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("Ventas", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.VentaPagoDetalle", b =>
                {
                    b.Property<long>("VentaPagoDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_VentaPagoDetalle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VentaPagoDetalleId"));

                    b.Property<long>("IdTipoPago")
                        .HasColumnType("bigint")
                        .HasColumnName("id_TipoPago");

                    b.Property<long>("IdVenta")
                        .HasColumnType("bigint")
                        .HasColumnName("id_Venta");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto");

                    b.HasKey("VentaPagoDetalleId");

                    b.HasIndex("IdTipoPago");

                    b.HasIndex("IdVenta");

                    b.ToTable("VentaPagoDetalles", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.DetallesVenta", b =>
                {
                    b.HasOne("AccesoDatos.Entidades.Producto", "Producto")
                        .WithMany("DetallesVentas")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccesoDatos.Entidades.Venta", "Venta")
                        .WithMany("DetallesVentas")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Empleado", b =>
                {
                    b.HasOne("AccesoDatos.Entidades.Persona", "Persona")
                        .WithOne()
                        .HasForeignKey("AccesoDatos.Entidades.Empleado", "PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.EmpleadoRol", b =>
                {
                    b.HasOne("AccesoDatos.Entidades.Empleado", "Empleado")
                        .WithMany("EmpleadoRoles")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccesoDatos.Entidades.Rol", "Rol")
                        .WithMany("EmpleadosRoles")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Movimiento", b =>
                {
                    b.HasOne("AccesoDatos.Entidades.Venta", "Venta")
                        .WithMany()
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Producto", b =>
                {
                    b.HasOne("AccesoDatos.Entidades.Categoria", null)
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId");

                    b.HasOne("AccesoDatos.Entidades.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AccesoDatos.Entidades.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AccesoDatos.Entidades.Marca", null)
                        .WithMany("Productos")
                        .HasForeignKey("MarcaId");

                    b.Navigation("Categoria");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Venta", b =>
                {
                    b.HasOne("AccesoDatos.Entidades.Empleado", "Empleado")
                        .WithMany("Ventas")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.VentaPagoDetalle", b =>
                {
                    b.HasOne("AccesoDatos.Entidades.TipoPago", "TipoPago")
                        .WithMany()
                        .HasForeignKey("IdTipoPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccesoDatos.Entidades.Venta", "Venta")
                        .WithMany("VentaPagoDetalles")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoPago");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Empleado", b =>
                {
                    b.Navigation("EmpleadoRoles");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Marca", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Producto", b =>
                {
                    b.Navigation("DetallesVentas");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Rol", b =>
                {
                    b.Navigation("EmpleadosRoles");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Venta", b =>
                {
                    b.Navigation("DetallesVentas");

                    b.Navigation("VentaPagoDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
