// <auto-generated />
using System;
using AccesoDatos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccesoDatos.Migrations
{
    [DbContext(typeof(GestorContextDB))]
    [Migration("20260203215939_BorrarMovCteCteYVincularMovimiento")]
    partial class BorrarMovCteCteYVincularMovimiento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccesoDatos.Entidades.Caja", b =>
                {
                    b.Property<long>("CajaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CajaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CajaId"));

                    b.Property<decimal>("BalanceFinal")
                        .HasColumnType("decimal")
                        .HasColumnName("balance_final");

                    b.Property<long>("EmpleadoApertura")
                        .HasColumnType("bigint")
                        .HasColumnName("empleado_apertura");

                    b.Property<long?>("EmpleadoCierre")
                        .HasColumnType("bigint")
                        .HasColumnName("empleado_cierre");

                    b.Property<bool>("EstaCerrada")
                        .HasColumnType("bit")
                        .HasColumnName("esta_cerrada");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_cierre");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_apertura");

                    b.Property<decimal>("SaldoActual")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("saldo_actual");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("saldo_inicial");

                    b.Property<decimal>("TotalEgresos")
                        .HasColumnType("decimal")
                        .HasColumnName("total_egresos");

                    b.Property<decimal>("TotalIngresos")
                        .HasColumnType("decimal")
                        .HasColumnName("total_ingresos");

                    b.HasKey("CajaId");

                    b.ToTable("Cajas", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Categoria", b =>
                {
                    b.Property<long>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CategoriaId"));

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.CategoriaProducto", b =>
                {
                    b.Property<long>("CategoriaProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CategoriaProductoId"));

                    b.Property<long>("IdCategoria")
                        .HasColumnType("bigint");

                    b.Property<long>("IdProducto")
                        .HasColumnType("bigint");

                    b.HasKey("CategoriaProductoId");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdProducto");

                    b.ToTable("Categorias_Productos", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Cliente", b =>
                {
                    b.Property<long>("PersonaId")
                        .HasColumnType("bigint")
                        .HasColumnName("PersonaId");

                    b.Property<long?>("CuentaCorrienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("CuentaCorrienteId");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<string>("EstadoDescripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("estado_descripcion");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("date")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("date")
                        .HasColumnName("fecha_baja");

                    b.Property<string>("NumeroCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("numero_cliente");

                    b.HasKey("PersonaId");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.CuentaCorriente", b =>
                {
                    b.Property<long>("CuentaCorrienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CuentaCorrienteId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CuentaCorrienteId"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("ClienteId");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit")
                        .HasColumnName("esta_eliminado");

                    b.Property<int>("EstadoCuentaCorriente")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<decimal>("LimiteDeuda")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("limite_deuda");

                    b.Property<bool>("LimiteDeudaActivo")
                        .HasColumnType("bit")
                        .HasColumnName("limite_deuda_activo");

                    b.Property<string>("NombreCuentaCorriente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_cuenta_corriente");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("saldo");

                    b.HasKey("CuentaCorrienteId");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("CuentasCorrientes", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.CuentaCorrienteAutorizado", b =>
                {
                    b.Property<long>("CuentaCorrienteAutorizadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CuentaCorrienteAutorizadoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CuentaCorrienteAutorizadoId"));

                    b.Property<long>("CuentaCorrienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("CuentaCorrienteId");

                    b.Property<long>("Dni")
                        .HasColumnType("bigint")
                        .HasColumnName("dni");

                    b.HasKey("CuentaCorrienteAutorizadoId");

                    b.HasIndex("CuentaCorrienteId");

                    b.ToTable("CuentaCorrienteAutorizados", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.DetallesVenta", b =>
                {
                    b.Property<long>("DetalleVentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_DetalleVenta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DetalleVentaId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cantidad");

                    b.Property<long>("IdProducto")
                        .HasColumnType("bigint")
                        .HasColumnName("id_Producto");

                    b.Property<long>("IdVenta")
                        .HasColumnType("bigint")
                        .HasColumnName("id_Venta");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("DetalleVentaId");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdVenta");

                    b.ToTable("DetallesVenta", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Empleado", b =>
                {
                    b.Property<long>("PersonaId")
                        .HasColumnType("bigint")
                        .HasColumnName("PersonaId");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaEgreso")
                        .HasColumnType("date")
                        .HasColumnName("fechaEgreso");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("fechaIngreso");

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("legajo");

                    b.Property<string>("Pass")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("pass");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.Property<bool>("UsuarioEstaHabilitado")
                        .HasColumnType("bit")
                        .HasColumnName("usuarioestahabilitado");

                    b.HasKey("PersonaId");

                    b.ToTable("Empleados", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.EmpleadoRol", b =>
                {
                    b.Property<long>("EmpleadoRolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EmpleadoRolId"));

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("date");

                    b.Property<long>("IdEmpleado")
                        .HasColumnType("bigint");

                    b.Property<long>("IdRol")
                        .HasColumnType("bigint");

                    b.HasKey("EmpleadoRolId");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdRol");

                    b.ToTable("Empleados_Roles", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Gasto", b =>
                {
                    b.Property<long>("GastoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_Gasto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GastoId"));

                    b.Property<int>("CategoriaGasto")
                        .HasColumnType("int")
                        .HasColumnName("categoria_gasto");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("detalle");

                    b.Property<int>("EstadoGasto")
                        .HasColumnType("int")
                        .HasColumnName("estado_gasto");

                    b.Property<DateTime>("FechaGasto")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_gasto");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro");

                    b.Property<long>("IdEmpleado")
                        .HasColumnType("bigint")
                        .HasColumnName("id_Empleado");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_pagado");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_total");

                    b.Property<string>("NumeroGasto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("numero_gasto");

                    b.HasKey("GastoId");

                    b.HasIndex("CategoriaGasto");

                    b.HasIndex("EstadoGasto");

                    b.HasIndex("FechaGasto");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("Gastos", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Marca", b =>
                {
                    b.Property<long>("MarcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MarcaId"));

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MarcaId");

                    b.ToTable("Marcas", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Movimiento", b =>
                {
                    b.Property<long>("MovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_Movimiento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MovimientoId"));

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit")
                        .HasColumnName("esta_eliminado");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_movimiento");

                    b.Property<long>("IdCaja")
                        .HasColumnType("bigint")
                        .HasColumnName("id_Caja");

                    b.Property<long?>("IdCuentaCorriente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_CuentaCorriente");

                    b.Property<long?>("IdVenta")
                        .HasColumnType("bigint")
                        .HasColumnName("id_Venta");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto");

                    b.Property<string>("NumeroMovimiento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("numero_movimiento");

                    b.Property<int>("TipoMovimiento")
                        .HasColumnType("int")
                        .HasColumnName("tipo_movimiento");

                    b.HasKey("MovimientoId");

                    b.HasIndex("IdCaja");

                    b.HasIndex("IdCuentaCorriente");

                    b.HasIndex("IdVenta");

                    b.ToTable("Movimientos", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.OfertaDescuento", b =>
                {
                    b.Property<long>("OfertaDescuentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_OfertaDescuento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OfertaDescuentoId"));

                    b.Property<decimal?>("CantidadLimiteDeStock")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cantidad_limite_de_stock");

                    b.Property<decimal?>("CantidadProductosDentroOferta")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cantidad_productos_dentro_oferta");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<decimal?>("DescuentoTotalFinal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("descuento_total_final");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("detalle");

                    b.Property<bool>("EsUnSoloProducto")
                        .HasColumnType("bit")
                        .HasColumnName("es_un_solo_producto");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("bit")
                        .HasColumnName("esta_activa");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("GrupoNombre")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("grupo_nombre");

                    b.Property<long?>("IdCategoria")
                        .HasColumnType("bigint")
                        .HasColumnName("id_categoria");

                    b.Property<long?>("IdMarca")
                        .HasColumnType("bigint")
                        .HasColumnName("id_marca");

                    b.Property<long?>("IdRubro")
                        .HasColumnType("bigint")
                        .HasColumnName("id_rubro");

                    b.Property<decimal?>("PorcentajeDescuento")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("porcentaje_descuento");

                    b.Property<decimal>("PrecioFinal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_final");

                    b.Property<decimal>("PrecioOriginal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_original");

                    b.Property<bool>("TieneLimiteDeStock")
                        .HasColumnType("bit")
                        .HasColumnName("tiene_limite_de_stock");

                    b.Property<bool>("esOfertaPorGrupo")
                        .HasColumnType("bit")
                        .HasColumnName("es_oferta_por_grupo");

                    b.HasKey("OfertaDescuentoId");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdMarca");

                    b.HasIndex("IdRubro");

                    b.ToTable("OfertasDescuentos", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Persona", b =>
                {
                    b.Property<long>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PersonaId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cuil")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono2")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PersonaId");

                    b.ToTable("Personas", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Producto", b =>
                {
                    b.Property<long>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ProductoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductoId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("CodigoBarra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codigo_barra");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsFraccionable")
                        .HasColumnType("bit")
                        .HasColumnName("es_fraccionable");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit")
                        .HasColumnName("esta_eliminado");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<long>("IdMarca")
                        .HasColumnType("bigint")
                        .HasColumnName("id_Marca");

                    b.Property<long>("IdRubro")
                        .HasColumnType("bigint")
                        .HasColumnName("id_Rubro");

                    b.Property<bool>("IvaIncluidoPrecioFinal")
                        .HasColumnType("bit")
                        .HasColumnName("iva_inluido_precio_final");

                    b.Property<string>("Medida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("medida");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_costo");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_venta");

                    b.Property<decimal>("Stock")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("stock");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("unidad_medida");

                    b.HasKey("ProductoId");

                    b.HasIndex("IdMarca");

                    b.HasIndex("IdRubro");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.ProductosEnOfertaDescuentos", b =>
                {
                    b.Property<long>("ProductosEnOfertaDescuentosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_ProductosEnOfertaDescuento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductosEnOfertaDescuentosId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cantidad");

                    b.Property<decimal>("CantidadVendidaPorLimite")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cantidad_vendida_por_limite");

                    b.Property<long>("OfertaId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_OfertaDescuento");

                    b.Property<decimal>("PrecioConDescuento")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_con_descuento");

                    b.Property<decimal>("PrecioOrginal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_original");

                    b.Property<long>("ProductoId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_Producto");

                    b.HasKey("ProductosEnOfertaDescuentosId");

                    b.HasIndex("OfertaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductosEnOfertaDescuentos", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Rol", b =>
                {
                    b.Property<long>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_Rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RolId"));

                    b.Property<string>("CodigoRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codigo_rol");

                    b.Property<string>("DetalleRol")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("detalleRol");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("RolId");

                    b.HasIndex("CodigoRol")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Rubro", b =>
                {
                    b.Property<long>("RubroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RubroId"));

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RubroId");

                    b.ToTable("Rubros", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.TipoPago", b =>
                {
                    b.Property<long>("TipoPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_TipoPago");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TipoPagoId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("detalle");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit");

                    b.Property<bool>("MetodoPagoHabilitado")
                        .HasColumnType("bit")
                        .HasColumnName("metodo_pago_habilitado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("NumeroReferencia")
                        .HasColumnType("int")
                        .HasColumnName("numero_referencia");

                    b.HasKey("TipoPagoId");

                    b.ToTable("TiposPago", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Venta", b =>
                {
                    b.Property<long>("VentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_Venta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VentaId"));

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("descuento");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("detalle");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_venta");

                    b.Property<long?>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cliente");

                    b.Property<long>("IdEmpleado")
                        .HasColumnType("bigint")
                        .HasColumnName("id_Empleado");

                    b.Property<long>("IdVendedor")
                        .HasColumnType("bigint")
                        .HasColumnName("id_Vendedor");

                    b.Property<decimal>("MontoAdeudado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_adeudado");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_pagado");

                    b.Property<string>("NumeroVenta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("numero_venta");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<decimal>("TotalSinDescuento")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_sin_descuento");

                    b.HasKey("VentaId");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdVendedor");

                    b.ToTable("Ventas", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.VentaPagoDetalle", b =>
                {
                    b.Property<long>("VentaPagoDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_VentaPagoDetalle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VentaPagoDetalleId"));

                    b.Property<long?>("IdGasto")
                        .HasColumnType("bigint")
                        .HasColumnName("id_Gasto");

                    b.Property<long>("IdTipoPago")
                        .HasColumnType("bigint")
                        .HasColumnName("id_TipoPago");

                    b.Property<long?>("IdVenta")
                        .HasColumnType("bigint")
                        .HasColumnName("id_Venta");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto");

                    b.HasKey("VentaPagoDetalleId");

                    b.HasIndex("IdGasto");

                    b.HasIndex("IdTipoPago");

                    b.HasIndex("IdVenta");

                    b.ToTable("VentaPagoDetalles", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Entidades.CategoriaProducto", b =>
                {
                    b.HasOne("AccesoDatos.Entidades.Categoria", "Categoria")
                        .WithMany("CategoriasProductos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccesoDatos.Entidades.Producto", "Producto")
                        .WithMany("CategoriasProductos")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Cliente", b =>
                {
                    b.HasOne("AccesoDatos.Entidades.Persona", "Persona")
                        .WithOne()
                        .HasForeignKey("AccesoDatos.Entidades.Cliente", "PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.CuentaCorriente", b =>
                {
                    b.HasOne("AccesoDatos.Entidades.Cliente", "Cliente")
                        .WithOne("CuentaCorriente")
                        .HasForeignKey("AccesoDatos.Entidades.CuentaCorriente", "ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.CuentaCorrienteAutorizado", b =>
                {
                    b.HasOne("AccesoDatos.Entidades.CuentaCorriente", null)
                        .WithMany("CuentaCorrienteAutorizado")
                        .HasForeignKey("CuentaCorrienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccesoDatos.Entidades.DetallesVenta", b =>
                {
                    b.HasOne("AccesoDatos.Entidades.Producto", "Producto")
                        .WithMany("DetallesVentas")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccesoDatos.Entidades.Venta", "Venta")
                        .WithMany("DetallesVentas")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Empleado", b =>
                {
                    b.HasOne("AccesoDatos.Entidades.Persona", "Persona")
                        .WithOne()
                        .HasForeignKey("AccesoDatos.Entidades.Empleado", "PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.EmpleadoRol", b =>
                {
                    b.HasOne("AccesoDatos.Entidades.Empleado", "Empleado")
                        .WithMany("EmpleadoRoles")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccesoDatos.Entidades.Rol", "Rol")
                        .WithMany("EmpleadosRoles")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Gasto", b =>
                {
                    b.HasOne("AccesoDatos.Entidades.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Movimiento", b =>
                {
                    b.HasOne("AccesoDatos.Entidades.Caja", "Caja")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdCaja")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccesoDatos.Entidades.CuentaCorriente", "CuentaCorriente")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdCuentaCorriente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AccesoDatos.Entidades.Venta", "Venta")
                        .WithMany()
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Caja");

                    b.Navigation("CuentaCorriente");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.OfertaDescuento", b =>
                {
                    b.HasOne("AccesoDatos.Entidades.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AccesoDatos.Entidades.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AccesoDatos.Entidades.Rubro", "Rubro")
                        .WithMany()
                        .HasForeignKey("IdRubro")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("Marca");

                    b.Navigation("Rubro");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Producto", b =>
                {
                    b.HasOne("AccesoDatos.Entidades.Marca", "Marca")
                        .WithMany("Productos")
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccesoDatos.Entidades.Rubro", "Rubro")
                        .WithMany("Productos")
                        .HasForeignKey("IdRubro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");

                    b.Navigation("Rubro");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.ProductosEnOfertaDescuentos", b =>
                {
                    b.HasOne("AccesoDatos.Entidades.OfertaDescuento", "Oferta")
                        .WithMany("Productos")
                        .HasForeignKey("OfertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccesoDatos.Entidades.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Oferta");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Venta", b =>
                {
                    b.HasOne("AccesoDatos.Entidades.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AccesoDatos.Entidades.Empleado", "Empleado")
                        .WithMany("Ventas")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccesoDatos.Entidades.Empleado", "Vendedor")
                        .WithMany()
                        .HasForeignKey("IdVendedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.VentaPagoDetalle", b =>
                {
                    b.HasOne("AccesoDatos.Entidades.Gasto", "Gasto")
                        .WithMany("VentaPagoDetalles")
                        .HasForeignKey("IdGasto")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AccesoDatos.Entidades.TipoPago", "TipoPago")
                        .WithMany()
                        .HasForeignKey("IdTipoPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccesoDatos.Entidades.Venta", "Venta")
                        .WithMany("VentaPagoDetalles")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Gasto");

                    b.Navigation("TipoPago");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Caja", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Categoria", b =>
                {
                    b.Navigation("CategoriasProductos");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Cliente", b =>
                {
                    b.Navigation("CuentaCorriente")
                        .IsRequired();
                });

            modelBuilder.Entity("AccesoDatos.Entidades.CuentaCorriente", b =>
                {
                    b.Navigation("CuentaCorrienteAutorizado");

                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Empleado", b =>
                {
                    b.Navigation("EmpleadoRoles");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Gasto", b =>
                {
                    b.Navigation("VentaPagoDetalles");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Marca", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.OfertaDescuento", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Producto", b =>
                {
                    b.Navigation("CategoriasProductos");

                    b.Navigation("DetallesVentas");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Rol", b =>
                {
                    b.Navigation("EmpleadosRoles");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Rubro", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("AccesoDatos.Entidades.Venta", b =>
                {
                    b.Navigation("DetallesVentas");

                    b.Navigation("VentaPagoDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
